allow-licenses:
  - 'Apache-2.0'
  - 'BSD-2-Clause'
  - 'BSD-2-Clause-FreeBSD'
  - 'BSD-3-Clause'
  - 'MIT'
  - 'ISC'
  - 'Python-2.0'
  - 'PostgreSQL'
  - 'X11'
  - 'Zlib'

allow_dependencies_licenses:
 - github.com/hashicorp/go-retryablehttp
 - github.com/hashicorp/errwrap
 - github.com/hashicorp/go-cleanhttp
 - github.com/hashicorp/go-multierror
