github_actions:
  - changed-files:
      - any-glob-to-any-file: ['.github/**', 'scripts/**']

testing:
  - changed-files:
      - any-glob-to-any-file: ['integration/**', '**/*_test.go']

benchmarking:
  - changed-files:
      - any-glob-to-any-file: ['benchmark/**']

dependencies:
  - changed-files:
      - any-glob-to-any-file: ['**/go.mod', '**/go.sum']
