name: Pre-build

on:
  push:
    branches: ['main', 'release/**']
  pull_request:
    branches: ['main', 'release/**']

env:
  GO_VERSION: '1.21.9'

jobs:
  check-dco:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          # check-dco will check the last 20 commits, but commit ranges
          # exclude the start commit in the result, but need that commit
          # in order to calculate the range. i.e. HEAD~20..HEAD includes
          # 20 commits, but including HEAD it needs 21 commits.
          fetch-depth: 21
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: wget https://github.com/google/flatbuffers/releases/download/v22.9.29/Linux.flatc.binary.g++-10.zip
      - run: unzip Linux.flatc.binary.g++-10.zip
      - run: ./scripts/install-check-tools.sh
      - run: ./scripts/check-dco.sh
      - run: PATH=$PATH:$(pwd) ./scripts/check-flatc.sh

  check-git-secrets:
    runs-on: ubuntu-20.04
    steps:
      - name: Pull latest awslabs/git-secrets repo
        uses: actions/checkout@v4
        with:
          repository: awslabs/git-secrets
          ref: 1.3.0
          fetch-tags: true
          path: git-secrets
      - name: Install git secrets from source
        run: sudo make install
        working-directory: git-secrets
      - uses: actions/checkout@v4
      - name: Scan repository for git secrets
        run: |
          git secrets --register-aws
          git secrets --scan-history

  check-copyright-headers:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: ./scripts/install-check-tools.sh
      - run: ./scripts/check-ltag.sh

  check-licensing:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install go-licenses
        shell: bash
        run: go install github.com/google/go-licenses@v1.6.0
      - name: Check licenses
        shell: bash
        run: |
          allowed_licenses="Apache-2.0,BSD-2-Clause,BSD-2-Clause-FreeBSD,\
            BSD-3-Clause,ISC,MIT,MPL-2.0,PostgreSQL,Python-2.0,X11,Zlib"
          go-licenses check --include_tests  ${{ github.workspace }}/... \
            --allowed_licenses="${allowed_licenses}"

  yamllint:
    name: yamllint-lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: yamllint .
