name: Review dependencies

on:
  pull_request:
    branches: ['main', 'release/**']
    paths:
      - 'go.*'

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          config-file: './.github/dependency-review-config.yml'
