name: Update getting started guide

on:
  release:
    types: ['released']
  pull_request:
    branches: ['main', 'release/**']
    paths:
      # Run workflow on changes to the workflow definition itself to spot check
      # the core version update functionality.
      - '.github/workflows/update-getting-started-guide.yml'
      - 'scripts/assert-getting-started-guide-version-diff.sh'
      # Run workflow on changes to the getting started guide to validate
      # changes to the documentation do not break the update workflow.
      - 'docs/getting-started.md'
env:
  RELEASE_TAG: ''

jobs:
  test-update-version:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions/update-getting-started/
            docs/getting-started.md
            scripts/assert-getting-started-guide-version-diff.sh

      - name: Mock release tag on pull request
        run: echo "RELEASE_TAG=v0.0.0-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - uses: ./.github/actions/update-getting-started
        with:
          version: ${{ env.RELEASE_TAG }}

      - name: Assert version was updated correctly
        if: github.event_name == 'pull_request'
        run: bash scripts/assert-getting-started-guide-version-diff.sh ${{ env.RELEASE_TAG }}

  update-version:
    if: github.event_name == 'release'
    runs-on: ubuntu-20.04

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: |
            .github/actions/update-getting-started/
            docs/getting-started.md

      - name: Set published release tag
        run: echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - uses: ./.github/actions/update-getting-started
        with:
          version: ${{ env.RELEASE_TAG }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: 'Update getting started to ${{ github.event.release.tag_name }}'
          commit-message: 'Update getting started to ${{ github.event.release.tag_name }}'
          body: |
            This PR must be closed and reopened manually to trigger automated checks.

            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: easy-to-review, automated-pr
          token: ${{ secrets.GITHUB_TOKEN }}
          author: "GitHub <no-reply@github.com>"
          signoff: true
          branch: 'create-pull-request/update-getting-started-version-to-${{ github.event.release.tag_name }}'
          base: main
          delete-branch: true
