name: Update getting started guide

on:
  release:
    types: ['released']
  pull_request:
    branches: ['main', 'release/**']
    paths:
      - '.github/workflows/update-getting-started-guide.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  update-version:
    runs-on: ubuntu-20.04
    env:
      RELEASE_VERSION: ''
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            docs
      - name: Mock release tag on pull request
        if: github.event_name == 'pull_request'
        run: echo "RELEASE_VERSION=0.0.0-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      - name: Set published release tag
        if: github.event_name == 'release'
        run: |
          release_tag=${{ github.event.release.tag_name }}
          release_version=${release_tag/v/}
          echo "RELEASE_VERSION=${release_version}" >> $GITHUB_ENV
      - uses: ./.github/actions/update-getting-started
        with:
          version: ${{ env.RELEASE_VERSION }}
      - name: Create PR
        if: github.event_name == 'release'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          signoff: true
          title: 'Update getting started to ${{ github.event.release.tag_name }}'
          body: |
            Full changelog available at ${{ github.event.release.url }}

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
