name: Update getting started guide

on:
  release:
    types: ['released']
  pull_request:
    branches: ['main', 'release/**']
    paths:
      # Run workflow on changes to the workflow definition itself to spot check
      # the core release version update functionality.
      - '.github/workflows/update-getting-started-guide.yml'
      # Run workflow on changes to the getting started guide to verify if any
      # changes to the documentation do not break the update automation.
      - 'docs/getting-started.md'

permissions:
  pull-requests: write

jobs:
  update-version:
    runs-on: ubuntu-20.04
    env:
      RELEASE_TAG: ''
    steps:
      - uses: actions/checkout@v4

      - name: Mock release tag on pull request
        if: github.event_name == 'pull_request'
        run: echo "RELEASE_TAG=v0.0.0-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Set published release tag
        if: github.event_name == 'release'
        run: echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Update getting started version
        run: |
          release_tag=${{ env.RELEASE_TAG }}
          release_version=${release_tag/v/}
          sed -i -E "s/version=\"([0-9]+\.){2}[0-9]+\"/version=\"${release_version}\"/" docs/getting-started.md

      - name: Assert version was updated correctly
        if: github.event_name == 'pull_request'
        run: |
          release_tag=${{ env.RELEASE_TAG }}
          release_version=${release_tag/v/}
          output=$(git diff --exit-code) && {
            echo "Error: no changes made; expected getting started version to be updated to \"${release_version}\"" && exit 1
          } || {
            echo ${output}
            if [[ "${output}" =~ "+version=\"${release_version}\"" ]]; then
              echo "Diff looks good!"
            else
              echo "Error: release version not set properly" && exit 1
            fi
          }

      - name: Create PR
        if: github.event_name == 'release'
        uses: peter-evans/create-pull-request@v6
        with:
          title: 'Update getting started to ${{ github.event.release.tag_name }}'
          commit-message: 'Update getting started to ${{ github.event.release.tag_name }}'
          body: |
            This PR must be closed and reopened manually to trigger automated checks.

            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: easy-to-review, automated-pr
          token: ${{ secrets.GITHUB_TOKEN }}
          author: "GitHub <no-reply@github.com>"
          signoff: true
          branch: 'create-pull-request/update-getting-started-version-to-${{ github.event.release.tag_name }}'
          base: main
          delete-branch: true
